interview_quiz/urls.py
from django.conf import settings
from django.conf.urls import handler404
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from graphene_django.views import GraphQLView
from rest_framework import routers
from rest_framework.permissions import AllowAny

from api_rest.api import QuestionCategoryViewSet, QuestionViewSet, PostViewSet, UserViewSet
from questions.views import MainView, my_handler404
from drf_yasg2.views import get_schema_view
from drf_yasg2 import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Interview Quiz",
      default_version='2.0',
      description="Documentation to Interview Quiz, my pet project",
      contact=openapi.Contact(email="inspiracion@yandex.ru"),
      license=openapi.License(name="MIT License"),
   ),
   public=True,
   permission_classes=(AllowAny,)
)

router = routers.DefaultRouter()
router.register('categories', QuestionCategoryViewSet)
router.register('questions', QuestionViewSet)
router.register('posts', PostViewSet)
router.register('users', UserViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainView.as_view(), name='index'),
    path('questions/', include('questions.urls', namespace='questions')),
    path('users/', include('users.urls', namespace='users')),
    path('myadmin/', include('myadmin.urls', namespace='myadmin')),
    path('posts/', include('posts.urls', namespace='posts')),

    path('', include('social_django.urls', namespace='social')),

    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include(router.urls)),

    re_path(r'^swagger(?P<format>\.json|\.yaml)$',
    schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0),
    name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0),
    name='schema-redoc'),

    path('graphql/', GraphQLView.as_view(graphiql=True)),
]

handler404 = 'questions.views.my_handler404'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r'^__debug_/', include(debug_toolbar.urls))]
    urlpatterns += [path('404/', my_handler404, kwargs={'exception':
                                                            Exception('Page not Found')}, name='page_404')]

myadmin/urls.py
"""Sets associations of myadmin application urls with their views.

Attributes:

    * app_name (str): the name of a specific web application used in different parts of the overall structure.
    * urlpatterns(list): a list of paths that determine the behavior of a web application
                        when using the urls specified in the list.

"""

from django.urls import path

from .views import AdminPanelView, UserListView, UserUpdateView, UserDeleteView, \
    UserCreateView, CategoriesListView, CategoriesUpdateView, \
    CategoriesCreateView, CategoriesDeleteView, QuestionListView, QuestionCreateView, QuestionUpdateView, \
    QuestionDeleteView, PostListView, PostCreateView, PostUpdateView, PostDeleteView, UserIsStaff, \
    AdminsSearchQuestionView, AdminsSearchPostView, AdminsSearchUserView, AdminsSearchCategoryView, \
    AllTagsQuestionsView, ListQuestionsByTagView, AllTagsPostsView, ListPostsByTagView

app_name = 'myadmin'
urlpatterns = [
    path('', AdminPanelView.as_view(), name='admins_index'),
    path('users/', UserListView.as_view(), name='admins_users'),
    path('users-create/', UserCreateView.as_view(), name='admins_user_create'),
    path('users-update/<uuid:pk>/', UserUpdateView.as_view(), name='admins_user_update'),
    path('users-delete/<uuid:pk>/', UserDeleteView.as_view(), name='admins_user_delete'),

    path('users-is-staff/<uuid:pk>/', UserIsStaff.as_view(), name='admins_user_is_staff'),

    path('categories/', CategoriesListView.as_view(), name='admins_categories'),
    path('categories-create/', CategoriesCreateView.as_view(), name='admins_category_create'),
    path('categories-update/<int:pk>/', CategoriesUpdateView.as_view(), name='admins_category_update'),
    path('categories-delete/<int:pk>/', CategoriesDeleteView.as_view(), name='admins_category_delete'),

    path('questions/', QuestionListView.as_view(), name='admins_questions'),
    path('questions-create/', QuestionCreateView.as_view(), name='admins_question_create'),
    path('questions-update/<int:pk>/', QuestionUpdateView.as_view(), name='admins_question_update'),
    path('questions-delete/<int:pk>/', QuestionDeleteView.as_view(), name='admins_question_delete'),
    path('questions-tags/', AllTagsQuestionsView.as_view(), name='admins_question_tags'),
    path('questions-by-tag/<str:pk>/', ListQuestionsByTagView.as_view(), name='admins_questions_by_tag'),

    path('posts/', PostListView.as_view(), name='admins_posts'),
    path('posts-create/', PostCreateView.as_view(), name='admins_post_create'),
    path('posts-update/<int:pk>/', PostUpdateView.as_view(), name='admins_post_update'),
    path('posts-delete/<int:pk>/', PostDeleteView.as_view(), name='admins_post_delete'),
    path('posts-tags/', AllTagsPostsView.as_view(), name='admins_post_tags'),
    path('posts-by-tag/<str:pk>/', ListPostsByTagView.as_view(), name='admins_posts_by_tag'),

    path('search/user/', AdminsSearchUserView.as_view(), name='admins_search_results_user'),
    path('search/cat/', AdminsSearchCategoryView.as_view(), name='admins_search_results_category'),
    path('search/question/', AdminsSearchQuestionView.as_view(), name='admins_search_results_question'),
    path('search/post/', AdminsSearchPostView.as_view(), name='admins_search_results_post'),
]

posts/urls.py
"""Sets associations of posts application urls with their views.

Attributes:

    * app_name (str): the name of a specific web application used in different parts of the overall structure.
    * urlpatterns(list): a list of paths that determine the behavior of a web application
                         when using the urls specified in the list.
"""
from django.urls import path

from .views import PostView, PostsCategoryView, UserPostView, TagPostView, CategoryPostView, SearchPostView

app_name = 'posts'
urlpatterns = [
    path('all/', PostsCategoryView.as_view(), name='all'),
    path('post/<int:pk>/', PostView.as_view(), name='post'),
    path('user_posts/<uuid:pk>/', UserPostView.as_view(), name='user_posts'),
    path('tag_posts/<str:tag>/', TagPostView.as_view(), name='tag_posts'),
    path('category_posts/<int:pk>/', CategoryPostView.as_view(), name='category_posts'),

    path('search/', SearchPostView.as_view(), name='search_results_post'),
]

questions/urls.py
"""Sets associations of questions application urls with their views.

Attributes:

    * app_name (str): the name of a specific web application used in different parts of the overall structure.
    * urlpatterns(list): a list of paths that determine the behavior of a web application
                         when using the urls specified in the list.
"""

from django.urls import path

from questions.views import CategoryView, QuestionView, AllCategoriesView, \
    TimeIsUp, AnswerQuestion

app_name = 'questions'
urlpatterns = [
    path('categories/', AllCategoriesView.as_view(), name='categories'),
    path('start_test/<int:pk>/', CategoryView.as_view(), name='start_test'),
    path('test_body/<int:pk>/', QuestionView.as_view(), name='test_body'),
    path('answers/<int:item_id>/', AnswerQuestion.as_view(), name='answers'),
    path('time_is_up/', TimeIsUp.as_view(), name='time_is_up'),
]

users/urls.py
"""Sets associations of questions application urls with their views.

Attributes:

    * app_name (str): the name of a specific web application used in different parts of the overall structure.
    * urlpatterns(list): a list of paths that determine the behavior of a web application
                         when using the urls specified in the list.
"""
from django.urls import path, reverse_lazy

from .views import UserLoginView, RegisterView, UserLogoutView, UserEdit, UserImgEdit, \
    UserPostCreateView, UserQuestionCreateView, TopUsers, ProfileView, Verify, \
    FailedAuthenticationView, WriteToAdmin, UserPasswordResetView, MyPasswordResetCompleteView, \
    MyPasswordResetConfirmView, GiveMeMyButtons, UserNoInfo

app_name = 'users'
urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),

    path('register/', RegisterView.as_view(), name='register'),
    path('verify/<str:email>/<str:activation_key>/', Verify.as_view(), name='verify'),
    path('attempt_failed/<str:error>', FailedAuthenticationView.as_view(), name='failed'),

    path('password_reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_confirm/<uidb64>/<token>/', MyPasswordResetConfirmView.as_view(success_url=reverse_lazy(
        'users:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', MyPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile_edit/', UserEdit.as_view(), name='profile_edit'),
    path('profile_img_edit/', UserImgEdit.as_view(), name='profile_img_edit'),
    path('profile_buttons/', GiveMeMyButtons.as_view(), name='give_me_my_buttons'),

    path('posts_create/', UserPostCreateView.as_view(), name='user_post_create'),
    path('question_create/', UserQuestionCreateView.as_view(), name='user_question_create'),
    path('top_users/', TopUsers.as_view(), name='top_users'),
    path('write_to_admin/', WriteToAdmin.as_view(), name='write_to_admin'),

    path('no_info/', UserNoInfo.as_view(), name='no_info'),
]

questions/templates/questions/answers.html
{% extends 'questions/base.html' %}
{% load static %}


{% block content %}
    {% include 'questions/includes/modal.html' %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid text-center text-adaptive" id="test-catcher">
                <h1 class="mt-4 h1-title">Тема: <b class="oranged">{{ item.subject }}</b></h1>
                <div class="row main p-1 mt-1 justify-content-center">
                    <h2 class="h1-title">Ответ на вопрос {{ item.id }}</h2>
                </div>
                <div class="row main p-1 mt-1 justify-content-center">
                    {% if guessed %}
                        <div class="col-lg-12 m-1 guessed">
                            <h3>Верно!</h3>
                        </div>
                    {% else %}
                        <div class="col-lg-12 m-1 wrong">
                            <h3>Ошибка!</h3>
                        </div>
                    {% endif %}
                    <div class="col-md-6 border border-grey">
                        <div class="text-center">Ваш ответ:</div>
                        <div class="text-wrap text-justify text-break font-xl text-adaptive">
                            {{ chosen_answer }}
                        </div>
                    </div>
                    <div class="col-md-6 border border-grey">
                        <div class="text-center">Правильный ответ:</div>
                        <div class="text-wrap text-justify text-break font-xl text-adaptive">
                            {{ item.right_answer }}
                        </div>
                    </div>
                </div>
                <div class="row main p-1 mt-1 justify-content-center">
                    <div class="col-md-3 border border-grey">
                        {% include 'questions/includes/carousel.html' %}
                    </div>
                    <div class="col-md-7 border border-grey">
                        {% if posts %}
                            <div>Посты на эту тему:</div>
                            {% for post in posts %}
                                <ul class="list-group">
                                    <li class="list-group-item">
                                        <a href="{% url 'posts:post' post.id %}">{{ post.title }}</a>
                                    </li>
                                </ul>
                            {% endfor %}
                        {% else %}
                            <p>Постов на эту тему пока нет</p>
                        {% endif %}
                    </div>
                    <div class="col-md-2 border border-greyr">
                        <div class="text-center w-100">Ваш счет:</div>
                        <div class="w-100">
                            <h3 class="oranged">{{ user.score }}</h3>
                        </div>
                        {% if user.is_staff %}
                            <div>
                                <a class='btn btn-outline-dark btn-orange btn-block m-1'
                                   href='{% url 'myadmin:admins_question_update' item.id %}'>Редактировать вопрос</a>
                            </div>
                        {% endif %}
                    </div>

                </div>
                <div class="row main p-1 mt-1 justify-content-center">
                    <div class="col-md-6">
                        <a class='btn btn-primary btn-block m-1' href='{% url 'questions:categories' %}'>Закончить</a>
                    </div>
                    <div class="col-md-6">
                        <a class='btn btn-outline-dark btn-orange  btn-block m-1'
                           href='{% url 'questions:test_body' item.subject.id %}'>Дальше!</a>
                    </div>
                </div>
            </div>
        </main>
        {% include 'questions/includes/footer.html' %}
    </div>
{% endblock %}

questions/templates/questions/base.html
{% load static %}
{% load yandex_metrica %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/admin.css' %}" rel="stylesheet"/>
    {% yandex_metrica %}
</head>

<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand oranged" href="{% url 'index' %}">Главная</a>
    <button class="btn btn-link btn-md m-2 order-1 order-lg-0 btn-orange blacked" id="sidebarToggle"><i
            class="fas fa-bars"></i>
    </button>
    <!-- Navbar Search-->

    <form class="d-none d-md-inline-block form-inline ml-auto mr-0
    mr-md-3 my-2 my-md-0" action="{% url 'posts:search_results_post' %}" method="get">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Поиск по статьям"
                   name="search_panel" aria-label="Search" aria-describedby="basic-addon2"/>
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit"><i class="fas fa-search oranged"></i></button>
            </div>
        </div>
    </form>

    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle rounded btn-orange blacked" id="userDropdown" role="button"
               data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw blacked"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">

                {% if user.is_authenticated %}
                    <a class="dropdown-item" href="{% url 'users:logout' %}">Выйти из профиля</a>
                {% else %}
                    <a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a>
                    <a class="dropdown-item" href="{% url 'users:login' %}">Авторизация</a>
                {% endif %}

            </div>
        </li>
    </ul>
</nav>

<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Приложения</div>
                    <a class="nav-link" href="{% url 'questions:categories' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-boxes oranged"></i>
                        </div>
                        Категории тестов
                    </a>
                    <a class="nav-link" href="{% url 'posts:all' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-file-alt oranged"></i>
                        </div>
                        Статьи
                    </a>
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'users:profile' %}">
                            <div class="sb-nav-link-icon">
                                <i class="fa fa-user oranged"></i>
                            </div>
                            Мой профиль
                        </a>
                        <a id="my_profile"></a>
                    {% else %}
                        <a class="nav-link" href="{% url 'users:login' %}">
                            <div class="sb-nav-link-icon">
                                <i class="fa fa-user oranged"></i>
                            </div>
                            Авторизация на сайте
                        </a>
                    {% endif %}
                    {% if user.is_staff %}
                        <input type="button" class="btn btn-block btn-orange blacked"
                               onclick="window.location.href = '{% url 'myadmin:admins_index' %}';"
                               value="К админке"/>
                    {% endif %}
                    <button onClick="javascript:history.go(-1);" type="submit" class="btn btn-block btn-orange blacked">
                        <i class="fa fa-undo"></i> Назад
                    </button>
                </div>
            </div>
            <div class="sb-sidenav-footer"></div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</div>


<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<script src="{% static 'js/csrf.js' %}"></script>
<script src="{% static 'js/site_actions.js' %}"></script>
<script src="https://kit.fontawesome.com/2b537a4c3e.js" crossorigin="anonymous"></script>
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}"></script>
<script src="{% static 'js/auth-admin.js' %}"></script>

</body>
</html>

questions/templates/questions/categories.html
{% extends 'questions/base.html' %}
{% load static %}


{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid text-center">
                <h1 class="mt-4">Категории тестов</h1>
                {% for category in questioncategory_list %}
                    <div class="row main p-1 border border-grey mt-1">
                        <div class="col-md-4">
                            <div class="text-center header-h2 all-width">
                                <h2 class="oranged">{{ category.name }}</h2>
                            </div>
                            <img class="img-fluid img-rounded"
                                 src="{{ category.image_url }}" alt=""/>
                        </div>
                        <div class="col-md-8 mt-3">
                            <div class="container-fluid pt-4 pb-3 text-wrap text-justify text-break text-adaptive">
                                {{ category.description }}
                            </div>
                            <div class="row justify-content-center">
                                <a class='btn btn-primary all-width'
                                   href='{% url 'questions:start_test' category.id %}'>Тестируем {{ category.name }}</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </main>
        {% include 'questions/includes/footer.html' %}
    </div>
{% endblock %}

questions/templates/questions/page_not_found.html
{% extends 'questions/base.html' %}
{% load static %}

{% block content %}
    {% include 'questions/includes/modal.html' %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid text-center">
                <h1 class="mt-4 oranged h1-title">Ой!</h1>
                <h3 class="mt-4 h1-title">К сожалению, такая страница не существует, но когда-нибудь,
                    возможно, мы ее создадим!</h3>
                <div class="row mt-5">
                    <div class="col-12 mt-4">
                        <img width="100px"
                             src="{% static 'vendor/img/other/hourglass.png' %}" alt="">
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-lg-6 mt-1 mb-1">
                        <a class='btn btn-primary btn-block mt-3 mb-1' href="{% url 'questions:categories' %}">
                            Выбор категорий</a>
                    </div>
                    <div class="col-lg-6 mt-1 mb-1 ">
                        <a class='btn btn-primary btn-block mt-3 mb-1'
                           href="{% url 'index' %}">
                            На главную </a>
                    </div>
                </div>
            </div>
        </main>
        {% include 'questions/includes/footer.html' %}
    </div>
{% endblock %}

questions/templates/questions/test_body.html
{% extends 'questions/base.html' %}
{% load static %}
{% load question_methods %}

{% block content %}
    {% include 'questions/includes/modal.html' %}
    <div id="layoutSidenav_content">
        <main>
            {% if item %}
                {% if item == 'Stop' %}
                    <div class="container-fluid text-center text-adaptive">
                        <h1 class="mt-4 h1-title">Тестовый блок из <b class="oranged">{{ quantity }}</b> вопросов
                            закончен</h1>
                        <h3 class="mt-4 text-adaptive">Пройдите еще одно испытание или выберите другую тему и сложность
                            вопросов</h3>

                        <div> Правильных ответов - <b class="oranged">{{ right_ans }}</b></div>
                        <div> Неправильных ответов - <b class="oranged">{{ wrong_ans }}</b></div>
                        <div class="mt-4">
                            <div class="row mt-3">
                                <div class="col-lg-6">
                                    <a class='btn btn-primary btn-block mt-3 mb-1'
                                       href="{% url 'questions:categories' %}">
                                        Выбор категорий</a>
                                </div>
                                <div class="col-lg-6">
                                    <a class='btn btn-primary btn-block mt-3 mb-1'
                                       href="{% url 'questions:start_test' category.id %}">
                                        Выбор сложности {{ category }}</a>
                                </div>
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-12 mb-4">
                                <img width="100px"
                                     src="{% static 'vendor/img/other/hourglass.png' %}" alt="">
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="container-fluid text-center" id="test-catcher">
                        <div class="row">
                            <div class="col-11">
                                <h1 class="mt-4 h1-title">Тема: <b class="oranged">{{ current_category }}</b></h1>
                            </div>
                            {% if limit == 'True' %}
                                <div class="col-1 mt-4">
                                    <div class="row">
                                        <p class="oranged font-xl mr-2" id="time_counter"></p>
                                        <img width="25px" src="{% static 'vendor/img/other/hourglass.png' %}" alt="">
                                    </div>
                                </div>
                            {% endif %}


                        </div>
                        <div class="container-fluid mb-5 text-adaptive">
                            <div class="row flex-md-row pt-2 pb-2 justify-content-center">
                                <div class="col-lg-2">Цена вопроса: <b class="oranged">{{ dif_points }}</b></div>
                                <div class="col-lg-8">
                                    <h2 class="h1-title">Вопрос № {{ item.id }}</h2>
                                </div>
                                <div class="col-lg-2">Ваш счет: <b class="oranged">{{ user_points }}</b></div>
                            </div>
                            <div class="row main p-1 border border-grey mt-1">
                                <div class="col-lg-3 thumbnail">
                                    <img class="card-img-top img-thumbnail"
                                         src="


                                                 {% if item.image_01 %}{{ item.image_01.url }}{% else %} {% static 'vendor/img/no_image.png' %} {% endif %}"
                                         alt="">
                                </div>
                                <div class="col-lg-9 mt-3 form-adaptive-width">
                                    <div class="form-adaptive-width text-wrap text-justify text-break">
                                        {{ item.question }}
                                    </div>
                                </div>
                            </div>
                            <div class="row main p-1 border border-grey mt-1">

                                <form method="get" value="{{ item.id }}"
                                      action="{% url 'questions:answers' item.id %}"
                                      class="answer_catcher w-100">
                                    {% csrf_token %}
                                    <div class="row main p-3 mt-1 text-wrap text-justify text-break">
                                        <div class="col-lg-6">
                                            <div class="form-check">
                                                <input class="form-check-input" name="answers" type="radio"
                                                       id="answer_01"
                                                       value="{{ item.answer_01 }}" checked>
                                                <label class="form-check-label" for="answer_01">
                                                    {{ item.answer_01 }}
                                                </label>
                                            </div>
                                            <div class="form-check">
                                                <input class="form-check-input" type="radio" name="answers"
                                                       id="answer_02"
                                                       value="{{ item.answer_02 }}">
                                                <label class="form-check-label" for="answer_02">
                                                    {{ item.answer_02 }}
                                                </label>
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-check">
                                                <input class="form-check-input" type="radio" name="answers"
                                                       id="answer_03"
                                                       value="{{ item.answer_03 }}">
                                                <label class="form-check-label" for="answer_03">
                                                    {{ item.answer_03 }}
                                                </label>
                                            </div>
                                            <div class="form-check">
                                                <input class="form-check-input" type="radio" name="answers"
                                                       id="answer_04"
                                                       value="{{ item.answer_04 }}">
                                                <label class="form-check-label" for="answer_04">
                                                    {{ item.answer_04 }}
                                                </label>
                                            </div>
                                        </div>
                                        <div class="col-lg-12 in-center mt-3">
                                            <button id="mybtn" type="submit" class="btn-block btn-lg btn-orange"
                                            >Отвечаю!
                                            </button>
                                        </div>
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>
                {% endif %}
            {% else %}
                <div class="container-fluid text-center">
                    <h1 class="mt-4">Вопросов пока нет</h1>
                    <h3 class="mt-4">Извините, вопросы категории <b
                            class="oranged">{{ category }}</b> уровня&nbsp;"<b
                            class="oranged">{{ dif|choice_name }}</b>"
                        еще&nbsp;не&nbsp;добавлены</h3>
                    <div class="row mt-5">
                        <div class="col-12 mt-4">
                            <img width="100px"
                                 src="{% static 'vendor/img/other/hourglass.png' %}" alt="">
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-6 mt-4">
                            <a class='btn btn-primary btn-block mt-3 mb-1' href="{% url 'questions:categories' %}">
                                Выбор категорий</a>
                        </div>
                        <div class="col-6 mt-4">
                            <a class='btn btn-primary btn-block mt-3 mb-1'
                               href="{% url 'questions:start_test' category.id %}">
                                Выбор сложности {{ category }}</a>
                        </div>
                    </div>
                </div>
            {% endif %}
        </main>
        {% include 'questions/includes/footer.html' %}
    </div>
{% endblock %}