interview_quiz/urls.py
from django.conf import settings
from django.conf.urls import handler404
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from graphene_django.views import GraphQLView
from rest_framework import routers
from rest_framework.permissions import AllowAny

from api_rest.api import QuestionCategoryViewSet, QuestionViewSet, PostViewSet, UserViewSet
from questions.views import MainView, my_handler404
from drf_yasg2.views import get_schema_view
from drf_yasg2 import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Interview Quiz",
      default_version='2.0',
      description="Documentation to Interview Quiz, my pet project",
      contact=openapi.Contact(email="inspiracion@yandex.ru"),
      license=openapi.License(name="MIT License"),
   ),
   public=True,
   permission_classes=(AllowAny,)
)

router = routers.DefaultRouter()
router.register('categories', QuestionCategoryViewSet)
router.register('questions', QuestionViewSet)
router.register('posts', PostViewSet)
router.register('users', UserViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainView.as_view(), name='index'),
    path('questions/', include('questions.urls', namespace='questions')),
    path('users/', include('users.urls', namespace='users')),
    path('myadmin/', include('myadmin.urls', namespace='myadmin')),
    path('posts/', include('posts.urls', namespace='posts')),

    path('', include('social_django.urls', namespace='social')),

    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include(router.urls)),

    re_path(r'^swagger(?P<format>\.json|\.yaml)$',
    schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0),
    name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0),
    name='schema-redoc'),

    path('graphql/', GraphQLView.as_view(graphiql=True)),
]

handler404 = 'questions.views.my_handler404'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r'^__debug_/', include(debug_toolbar.urls))]
    urlpatterns += [path('404/', my_handler404, kwargs={'exception':
                                                            Exception('Page not Found')}, name='page_404')]

myadmin/urls.py
"""Sets associations of myadmin application urls with their views.

Attributes:

    * app_name (str): the name of a specific web application used in different parts of the overall structure.
    * urlpatterns(list): a list of paths that determine the behavior of a web application
                        when using the urls specified in the list.

"""

from django.urls import path

from .views import AdminPanelView, UserListView, UserUpdateView, UserDeleteView, \
    UserCreateView, CategoriesListView, CategoriesUpdateView, \
    CategoriesCreateView, CategoriesDeleteView, QuestionListView, QuestionCreateView, QuestionUpdateView, \
    QuestionDeleteView, PostListView, PostCreateView, PostUpdateView, PostDeleteView, UserIsStaff, \
    AdminsSearchQuestionView, AdminsSearchPostView, AdminsSearchUserView, AdminsSearchCategoryView, \
    AllTagsQuestionsView, ListQuestionsByTagView, AllTagsPostsView, ListPostsByTagView

app_name = 'myadmin'
urlpatterns = [
    path('', AdminPanelView.as_view(), name='admins_index'),
    path('users/', UserListView.as_view(), name='admins_users'),
    path('users-create/', UserCreateView.as_view(), name='admins_user_create'),
    path('users-update/<uuid:pk>/', UserUpdateView.as_view(), name='admins_user_update'),
    path('users-delete/<uuid:pk>/', UserDeleteView.as_view(), name='admins_user_delete'),

    path('users-is-staff/<uuid:pk>/', UserIsStaff.as_view(), name='admins_user_is_staff'),

    path('categories/', CategoriesListView.as_view(), name='admins_categories'),
    path('categories-create/', CategoriesCreateView.as_view(), name='admins_category_create'),
    path('categories-update/<int:pk>/', CategoriesUpdateView.as_view(), name='admins_category_update'),
    path('categories-delete/<int:pk>/', CategoriesDeleteView.as_view(), name='admins_category_delete'),

    path('questions/', QuestionListView.as_view(), name='admins_questions'),
    path('questions-create/', QuestionCreateView.as_view(), name='admins_question_create'),
    path('questions-update/<int:pk>/', QuestionUpdateView.as_view(), name='admins_question_update'),
    path('questions-delete/<int:pk>/', QuestionDeleteView.as_view(), name='admins_question_delete'),
    path('questions-tags/', AllTagsQuestionsView.as_view(), name='admins_question_tags'),
    path('questions-by-tag/<str:pk>/', ListQuestionsByTagView.as_view(), name='admins_questions_by_tag'),

    path('posts/', PostListView.as_view(), name='admins_posts'),
    path('posts-create/', PostCreateView.as_view(), name='admins_post_create'),
    path('posts-update/<int:pk>/', PostUpdateView.as_view(), name='admins_post_update'),
    path('posts-delete/<int:pk>/', PostDeleteView.as_view(), name='admins_post_delete'),
    path('posts-tags/', AllTagsPostsView.as_view(), name='admins_post_tags'),
    path('posts-by-tag/<str:pk>/', ListPostsByTagView.as_view(), name='admins_posts_by_tag'),

    path('search/user/', AdminsSearchUserView.as_view(), name='admins_search_results_user'),
    path('search/cat/', AdminsSearchCategoryView.as_view(), name='admins_search_results_category'),
    path('search/question/', AdminsSearchQuestionView.as_view(), name='admins_search_results_question'),
    path('search/post/', AdminsSearchPostView.as_view(), name='admins_search_results_post'),
]

posts/urls.py
"""Sets associations of posts application urls with their views.

Attributes:

    * app_name (str): the name of a specific web application used in different parts of the overall structure.
    * urlpatterns(list): a list of paths that determine the behavior of a web application
                         when using the urls specified in the list.
"""
from django.urls import path

from .views import PostView, PostsCategoryView, UserPostView, TagPostView, CategoryPostView, SearchPostView

app_name = 'posts'
urlpatterns = [
    path('all/', PostsCategoryView.as_view(), name='all'),
    path('post/<int:pk>/', PostView.as_view(), name='post'),
    path('user_posts/<uuid:pk>/', UserPostView.as_view(), name='user_posts'),
    path('tag_posts/<str:tag>/', TagPostView.as_view(), name='tag_posts'),
    path('category_posts/<int:pk>/', CategoryPostView.as_view(), name='category_posts'),

    path('search/', SearchPostView.as_view(), name='search_results_post'),
]

users/urls.py
"""Sets associations of questions application urls with their views.

Attributes:

    * app_name (str): the name of a specific web application used in different parts of the overall structure.
    * urlpatterns(list): a list of paths that determine the behavior of a web application
                         when using the urls specified in the list.
"""
from django.urls import path, reverse_lazy

from .views import UserLoginView, RegisterView, UserLogoutView, UserEdit, UserImgEdit, \
    UserPostCreateView, UserQuestionCreateView, TopUsers, ProfileView, Verify, \
    FailedAuthenticationView, WriteToAdmin, UserPasswordResetView, MyPasswordResetCompleteView, \
    MyPasswordResetConfirmView, GiveMeMyButtons, UserNoInfo

app_name = 'users'
urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),

    path('register/', RegisterView.as_view(), name='register'),
    path('verify/<str:email>/<str:activation_key>/', Verify.as_view(), name='verify'),
    path('attempt_failed/<str:error>', FailedAuthenticationView.as_view(), name='failed'),

    path('password_reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_confirm/<uidb64>/<token>/', MyPasswordResetConfirmView.as_view(success_url=reverse_lazy(
        'users:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', MyPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile_edit/', UserEdit.as_view(), name='profile_edit'),
    path('profile_img_edit/', UserImgEdit.as_view(), name='profile_img_edit'),
    path('profile_buttons/', GiveMeMyButtons.as_view(), name='give_me_my_buttons'),

    path('posts_create/', UserPostCreateView.as_view(), name='user_post_create'),
    path('question_create/', UserQuestionCreateView.as_view(), name='user_question_create'),
    path('top_users/', TopUsers.as_view(), name='top_users'),
    path('write_to_admin/', WriteToAdmin.as_view(), name='write_to_admin'),

    path('no_info/', UserNoInfo.as_view(), name='no_info'),
]

myadmin/forms.py
"""Contains forms used to create or modify user, category, question, or post objects in the admin panel.
"""

from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

from posts.models import Post
from questions.models import QuestionCategory, Question
from users.forms import UserRegisterForm, UserProfileForm
from users.models import MyUser


class UserAdminRegisterForm(UserRegisterForm):
    """Form for creating a user from the admin panel.
    """
    img = forms.ImageField(widget=forms.FileInput, required=False)

    class Meta:
        """Defines the model involved and the fields used in the form.
        """
        model = MyUser
        fields = ('username', 'first_name', 'last_name', 'email',
                  'password1', 'password2', 'img',)

    def __init__(self, *args, **kwargs):
        """Manages the classes of form fields for their correct display on the page.
        """
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'img':
                field.widget.attrs['class'] = 'form-control'
            else:
                field.widget.attrs['class'] = 'form-control py-4'


class UserAdminProfileForm(UserProfileForm):
    """Form for editing a user profile from the admin panel.
    """

    def __init__(self, *args, **kwargs):
        """Manages the classes of form fields for their correct display on the page.
        Allows editing of 'username' and 'email' fields that are initially in read-only mode.
        """
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['readonly'] = False
        self.fields['email'].widget.attrs['readonly'] = False

        for field_name, field in self.fields.items():
            if field_name == 'img':
                field.widget.attrs['class'] = 'form-control'
            else:
                field.widget.attrs['class'] = 'form-control py-4'


class CategoryForm(ModelForm):
    """Form for creating and editing categories in the admin panel.
    """
    image = forms.ImageField(widget=forms.FileInput, required=False)

    class Meta:
        """Defines the model involved and the fields used in the form.
        """
        model = QuestionCategory
        fields = ['name', 'description', 'image']

    def __init__(self, *args, **kwargs):
        """Manages the classes of form fields for their correct display on the page.
        """
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'
        self.fields['image'].widget.attrs['class'] = 'form-control'


class QuestionForm(ModelForm):
    """Form for creating and editing questions in the admin panel.
    """
    error_messages = {
        'invalid_answer': _('Вы указали %(value)s как правильный ответ, но он не совпадает ни с одним '
                            'из предлагаемых вариантов ответа на вопрос'),
    }

    subject = forms.ModelChoiceField(queryset=QuestionCategory.objects.filter(available=True).select_related(),
                                     empty_label=None)
    image_01 = forms.ImageField(widget=forms.FileInput, required=False)
    image_02 = forms.ImageField(widget=forms.FileInput, required=False)
    image_03 = forms.ImageField(widget=forms.FileInput, required=False)

    class Meta:
        """Defines the model involved and the fields used in the form.
        """
        model = Question
        fields = ['question', 'subject', 'right_answer', 'answer_01', 'answer_02',
                  'answer_03', 'answer_04', 'difficulty_level', 'tag', 'image_01',
                  'image_02', 'image_03']

    def __init__(self, *args, **kwargs):
        """Manages the classes of form fields for their correct display on the page.
        """
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name in ['image_01', 'image_02', 'image_03', 'subject', 'difficulty_level']:
                field.widget.attrs['class'] = 'form-control'
            else:
                field.widget.attrs['class'] = 'form-control py-4'
        for item in ('image_01', 'image_02', 'image_03'):
            self.fields[item].widget.attrs['id'] = f'{item}'

    def clean(self):
        """Checks whether the correct answer matches one of the 4 options
        for user responses, if not, adds in form an error message, which will
        be displayed on the page to inform the user.
        """
        answer = self.cleaned_data.get('right_answer')
        a1 = self.cleaned_data.get('answer_01')
        a2 = self.cleaned_data.get('answer_02')
        a3 = self.cleaned_data.get('answer_03')
        a4 = self.cleaned_data.get('answer_04')
        if answer != a1 and answer != a2 and answer != a3 and answer != a4:
            msg = ValidationError(self.error_messages['invalid_answer'],
                                  code=f'invalid_answer',
                                  params={'value': answer})
            self.add_error('right_answer', msg)
        return self.cleaned_data


class PostForm(ModelForm):
    """Form for creating and editing posts in the admin panel.
    """
    category = forms.ModelChoiceField(queryset=QuestionCategory.objects.filter(available=True).select_related(),
                                      empty_label=None)
    image = forms.ImageField(widget=forms.FileInput, required=False)

    class Meta:
        """Defines the model involved and the fields used in the form.
        """
        model = Post
        fields = ['title', 'category', 'body', 'image',
                  'available', 'tag']

    def __init__(self, *args, **kwargs):
        """Manages the classes of form fields for their correct display on the page.
        """
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'image' or field_name == 'category':
                field.widget.attrs['class'] = 'form-control'
            else:
                field.widget.attrs['class'] = 'form-control py-4'
        self.fields['image'].widget.attrs['id'] = 'post_image'

myadmin/templates/myadmin/admin.html
{% extends 'myadmin/base.html' %}
{% load static %}


{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid text-center">
                <h1 class="mt-4">Административная панель</h1>
                <div class="row">
                    <div class="col-lg-6">
                        <form action="{% url 'myadmin:admins_users' %}">
                            <button type="submit" class="mt-1 big-admin-button container-fluid height-33"><i class="fas fa-users oranged fa-5x"></i></button>
                        </form>
                        <form action="{% url 'myadmin:admins_categories' %}">
                            <button type="submit" class="mt-1 big-admin-button container-fluid height-33"><i class="fas fa-boxes oranged fa-5x"></i></button>
                        </form>
                    </div>
                    <div class="col-lg-6">
                        <form action="{% url 'myadmin:admins_questions' %}">
                            <button type="submit" class="mt-1 big-admin-button container-fluid height-33"><i class="fa fa-question oranged fa-5x"></i></button>
                        </form>
                        <form action="{% url 'myadmin:admins_posts' %}">
                            <button type="submit" class="mt-1 big-admin-button container-fluid height-33"><i class="far fa-file-alt oranged fa-5x"></i></button>
                        </form>
                    </div>
                </div>
            </div>
        </main>
        {% include 'myadmin/includes/footer.html' %}
    </div>
{% endblock %}

myadmin/templates/myadmin/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/admin.css' %}" rel="stylesheet"/>
</head>

<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand oranged" href="{% url 'myadmin:admins_index' %}">Админка</a>
    <button class="btn btn-link btn-md m-2 order-1 order-lg-0 btn-orange blacked" id="sidebarToggle"><i
            class="fas fa-bars"></i>
    </button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0"
          action="{% url 'myadmin:admins_search_results_question' %}" method="get"
    id="catcher_admins_search_panel">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Поиск по вопросам"
                   aria-label="Search" name="admins_search_panel"
                   aria-describedby="basic-addon2" id="admins_search_panel"/>
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit"><i class="fas fa-search oranged"></i></button>
            </div>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle rounded btn-orange blacked" id="userDropdown" role="button"
               data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw blacked"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'myadmin:admins_user_update' user.id %}">Редактировать свой
                    профиль</a>
                <a class="dropdown-item" href="{% url 'users:logout' %}">Выйти из профиля</a>
            </div>
        </li>
    </ul>
</nav>

<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Приложения</div>
                    <a class="nav-link" href="{% url 'myadmin:admins_users' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-users oranged"></i>
                        </div>
                        Пользователи
                    </a>
                    <a class="nav-link" href="{% url 'myadmin:admins_categories' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-boxes oranged"></i>
                        </div>
                        Категории вопросов
                    </a>
                    <a class="nav-link" href="{% url 'myadmin:admins_questions' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fa fa-question oranged"></i>
                        </div>
                        Вопросы
                    </a>
                    <a class="nav-link" href="{% url 'myadmin:admins_posts' %}">
                        <div class="sb-nav-link-icon">
                            <i class="far fa-file-alt oranged"></i>
                        </div>
                        Статьи
                    </a>
                    <input type="button" class="btn btn-block btn-orange blacked"
                           onclick="window.location.href = '{% url 'index' %}';"
                           value="На главную"/>
                    <button onClick="javascript:history.go(-1);" type="submit" class="btn btn-block btn-orange blacked">
                        <i class="fa fa-undo"></i> Назад
                    </button>
                </div>
            </div>
            <div class="sb-sidenav-footer"></div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</div>


<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<script src="{% static 'js/csrf.js' %}"></script>
<script src="{% static 'js/site_actions.js' %}"></script>
<script src="https://kit.fontawesome.com/2b537a4c3e.js" crossorigin="anonymous"></script>
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}"></script>
<script src="{% static 'js/auth-admin.js' %}"></script>

</body>
</html>