interview_quiz/urls.py
from django.conf import settings
from django.conf.urls import handler404
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from graphene_django.views import GraphQLView
from rest_framework import routers
from rest_framework.permissions import AllowAny

from api_rest.api import QuestionCategoryViewSet, QuestionViewSet, PostViewSet, UserViewSet
from questions.views import MainView, my_handler404
from drf_yasg2.views import get_schema_view
from drf_yasg2 import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Interview Quiz",
      default_version='2.0',
      description="Documentation to Interview Quiz, my pet project",
      contact=openapi.Contact(email="inspiracion@yandex.ru"),
      license=openapi.License(name="MIT License"),
   ),
   public=True,
   permission_classes=(AllowAny,)
)

router = routers.DefaultRouter()
router.register('categories', QuestionCategoryViewSet)
router.register('questions', QuestionViewSet)
router.register('posts', PostViewSet)
router.register('users', UserViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainView.as_view(), name='index'),
    path('questions/', include('questions.urls', namespace='questions')),
    path('users/', include('users.urls', namespace='users')),
    path('myadmin/', include('myadmin.urls', namespace='myadmin')),
    path('posts/', include('posts.urls', namespace='posts')),

    path('', include('social_django.urls', namespace='social')),

    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include(router.urls)),

    re_path(r'^swagger(?P<format>\.json|\.yaml)$',
    schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0),
    name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0),
    name='schema-redoc'),

    path('graphql/', GraphQLView.as_view(graphiql=True)),
]

handler404 = 'questions.views.my_handler404'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r'^__debug_/', include(debug_toolbar.urls))]
    urlpatterns += [path('404/', my_handler404, kwargs={'exception':
                                                            Exception('Page not Found')}, name='page_404')]

myadmin/urls.py
"""Sets associations of myadmin application urls with their views.

Attributes:

    * app_name (str): the name of a specific web application used in different parts of the overall structure.
    * urlpatterns(list): a list of paths that determine the behavior of a web application
                        when using the urls specified in the list.

"""

from django.urls import path

from .views import AdminPanelView, UserListView, UserUpdateView, UserDeleteView, \
    UserCreateView, CategoriesListView, CategoriesUpdateView, \
    CategoriesCreateView, CategoriesDeleteView, QuestionListView, QuestionCreateView, QuestionUpdateView, \
    QuestionDeleteView, PostListView, PostCreateView, PostUpdateView, PostDeleteView, UserIsStaff, \
    AdminsSearchQuestionView, AdminsSearchPostView, AdminsSearchUserView, AdminsSearchCategoryView, \
    AllTagsQuestionsView, ListQuestionsByTagView, AllTagsPostsView, ListPostsByTagView

app_name = 'myadmin'
urlpatterns = [
    path('', AdminPanelView.as_view(), name='admins_index'),
    path('users/', UserListView.as_view(), name='admins_users'),
    path('users-create/', UserCreateView.as_view(), name='admins_user_create'),
    path('users-update/<uuid:pk>/', UserUpdateView.as_view(), name='admins_user_update'),
    path('users-delete/<uuid:pk>/', UserDeleteView.as_view(), name='admins_user_delete'),

    path('users-is-staff/<uuid:pk>/', UserIsStaff.as_view(), name='admins_user_is_staff'),

    path('categories/', CategoriesListView.as_view(), name='admins_categories'),
    path('categories-create/', CategoriesCreateView.as_view(), name='admins_category_create'),
    path('categories-update/<int:pk>/', CategoriesUpdateView.as_view(), name='admins_category_update'),
    path('categories-delete/<int:pk>/', CategoriesDeleteView.as_view(), name='admins_category_delete'),

    path('questions/', QuestionListView.as_view(), name='admins_questions'),
    path('questions-create/', QuestionCreateView.as_view(), name='admins_question_create'),
    path('questions-update/<int:pk>/', QuestionUpdateView.as_view(), name='admins_question_update'),
    path('questions-delete/<int:pk>/', QuestionDeleteView.as_view(), name='admins_question_delete'),
    path('questions-tags/', AllTagsQuestionsView.as_view(), name='admins_question_tags'),
    path('questions-by-tag/<str:pk>/', ListQuestionsByTagView.as_view(), name='admins_questions_by_tag'),

    path('posts/', PostListView.as_view(), name='admins_posts'),
    path('posts-create/', PostCreateView.as_view(), name='admins_post_create'),
    path('posts-update/<int:pk>/', PostUpdateView.as_view(), name='admins_post_update'),
    path('posts-delete/<int:pk>/', PostDeleteView.as_view(), name='admins_post_delete'),
    path('posts-tags/', AllTagsPostsView.as_view(), name='admins_post_tags'),
    path('posts-by-tag/<str:pk>/', ListPostsByTagView.as_view(), name='admins_posts_by_tag'),

    path('search/user/', AdminsSearchUserView.as_view(), name='admins_search_results_user'),
    path('search/cat/', AdminsSearchCategoryView.as_view(), name='admins_search_results_category'),
    path('search/question/', AdminsSearchQuestionView.as_view(), name='admins_search_results_question'),
    path('search/post/', AdminsSearchPostView.as_view(), name='admins_search_results_post'),
]

posts/urls.py
"""Sets associations of posts application urls with their views.

Attributes:

    * app_name (str): the name of a specific web application used in different parts of the overall structure.
    * urlpatterns(list): a list of paths that determine the behavior of a web application
                         when using the urls specified in the list.
"""
from django.urls import path

from .views import PostView, PostsCategoryView, UserPostView, TagPostView, CategoryPostView, SearchPostView

app_name = 'posts'
urlpatterns = [
    path('all/', PostsCategoryView.as_view(), name='all'),
    path('post/<int:pk>/', PostView.as_view(), name='post'),
    path('user_posts/<uuid:pk>/', UserPostView.as_view(), name='user_posts'),
    path('tag_posts/<str:tag>/', TagPostView.as_view(), name='tag_posts'),
    path('category_posts/<int:pk>/', CategoryPostView.as_view(), name='category_posts'),

    path('search/', SearchPostView.as_view(), name='search_results_post'),
]

myadmin/views.py
"""The submodule contains views for convenient and correct work with all the main entities of the
project within the admin panel.

There are views:

    * for standard work with objects according to the CRUD principle;
    * for searching for users, posts, categories and questions by a given mask (word or part of a word);
    * to grant or remove administrator rights to a user;

To reduce code duplication, two parent classes are used.
"""

from django.db.models import Q
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView

from interview_quiz.mixin import TitleMixin, UserDispatchMixin
from myadmin.forms import UserAdminRegisterForm, UserAdminProfileForm, CategoryForm, QuestionForm, PostForm
from posts.models import Post
from questions.models import QuestionCategory, Question
from users.models import MyUser


class BaseListView(ListView, TitleMixin, UserDispatchMixin):
    """Parent class for QuestionListView and PostListView, required to comply with the DRY pattern."""

    def get_context_data(self, *, object_list=None, **kwargs):
        """Provides getting and saving the current category selected by the user.
        The current category is saved in the session.
        When all categories are selected (no filter), the current category in the session is reset to zero.
        Set slided page range in context.
        """
        context = super().get_context_data(**kwargs)
        context['categories'] = QuestionCategory.objects.all()
        if self.request.GET.get('filter'):
            if self.request.GET.get('filter') == 'all':
                self.request.session['current_category'] = None
                return context
            context['current_category'] = QuestionCategory.objects.get(id=self.request.GET.get('filter')).name
            self.request.session['current_category'] = context['current_category']
        elif 'current_category' in self.request.session:
            context['current_category'] = self.request.session['current_category']
        page = context['page_obj']
        context['paginator_range'] = page.paginator.get_elided_page_range(page.number)
        return context


class BaseDeleteView(DeleteView, UserDispatchMixin):
    """Parent class for QuestionDeleteView and PostDeleteView, required to comply with the DRY pattern."""

    def delete(self, request, flag='false', *args, **kwargs):
        """Performs complete deletion or activation/deactivation of the object
        in accordance with the specified mode of action.

        Args:
            * request: standard parameter.
            * flag(str, optional): the default value is 'false'. A switch parameter that allows you
                                 to specify the mode of deleting an object: completely deleting an
                                 entry from the database or marking the object as inactive.
            * ``*args``: standard parameter.
            * ``**kwargs``: standard parameter.
        """
        item = self.get_object()
        if 'flag' in request.POST:
            flag = request.POST['flag']
        if flag == 'false':
            item.available = False if item.available is True else True
            item.save()
        else:
            item.delete()


class AdminPanelView(TemplateView, TitleMixin, UserDispatchMixin):
    """View for the main admin page."""
    template_name = 'myadmin/admin.html'
    title = 'Админка'


class UserListView(ListView, TitleMixin, UserDispatchMixin):
    """View to view lists of all registered users of the site in the admin panel."""
    model = MyUser
    template_name = 'myadmin/users/users-viewing.html'
    context_object_name = 'users'
    title = 'Просмотр пользователей'
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        """Set slided page range in context."""
        context = super().get_context_data(**kwargs)
        page = context['page_obj']
        context['paginator_range'] = page.paginator.get_elided_page_range(page.number)
        return context

    def get_queryset(self, order_val='date_joined'):
        """Returns ordered queryset.

        Args:
            * order_val (str): Selected order value.

        Returns:
            * Queryset of ordered objects.
        """
        if self.request.GET.get('user_order'):
            self.request.session['user_order'] = self.request.GET.get('user_order')
        if 'user_order' in self.request.session:
            order_val = self.request.session['user_order']
        return MyUser.objects.all().order_by(order_val)


class UserCreateView(CreateView, TitleMixin, UserDispatchMixin):
    """View to create a new user in the admin panel."""
    model = MyUser
    template_name = 'myadmin/users/users-creating.html'
    form_class = UserAdminRegisterForm
    success_url = reverse_lazy('myadmin:admins_users')
    title = 'Добавить пользователя'


class UserUpdateView(UpdateView, TitleMixin, UserDispatchMixin):
    """View to update a specific user in the admin panel."""
    model = MyUser
    template_name = 'myadmin/users/users-update.html'
    form_class = UserAdminProfileForm
    success_url = reverse_lazy('myadmin:admins_users')
    title = 'Изменить пользователя'


class UserDeleteView(DeleteView, UserDispatchMixin):
    """View to delete or activate/deactivate a specific user in the admin panel."""
    model = MyUser
    template_name = 'myadmin/users/users-update.html'
    success_url = reverse_lazy('myadmin:admins_users')

    def delete(self, request, flag='false', *args, **kwargs):
        """Performs complete deletion or activation/deactivation of the user
        in accordance with the specified mode of action.

        Args:
            * request: standard parameter.
            * flag(str, optional): the default value is 'false'. A switch parameter that allows you
                                 to specify the mode of deleting an object: completely deleting an
                                 entry from the database or marking the object as inactive.
            * ``*args``: standard parameter.
            * ``**kwargs``: standard parameter.
        """
        item = self.get_object()
        if 'flag' in request.POST:
            flag = request.POST['flag']
        if request.user.id != kwargs['pk']:
            if flag == 'false':
                item.is_active = False if item.is_active is True else True
                item.save()
            else:
                item.delete()

    def post(self, request, *args, **kwargs):
        """Starts the process of deleting or activating/deactivating user.
        When enabled ajax, returns data for an asynchronous web request"""
        self.delete(request, *args, **kwargs)
        if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
            uuids = request.POST.getlist('elements[]')

            page_obj = MyUser.objects.filter(id__in=uuids)
            context = {'page_obj': page_obj}

            result = render_to_string('myadmin/includes/table-users.html', request=request, context=context)
            return JsonResponse({'result': result})
        return HttpResponseRedirect(reverse('myadmin:admins_user_update', kwargs=kwargs))


class UserIsStaff(UpdateView, UserDispatchMixin):
    """View for granting the user rights/removing the rights of the superuser in the admin panel."""
    model = MyUser
    form_class = UserAdminProfileForm
    template_name = 'myadmin/includes/table-users.html'

    def post(self, request, *args, **kwargs):
        """Sets superuser rights for the selected user or deletes them.
        When enabled ajax, returns data for an asynchronous web request."""
        user = get_object_or_404(MyUser, pk=kwargs['pk'])
        if self.request.user != user:
            user.is_staff = False if user.is_staff is True else True
            user.save()
        uuids = request.POST.getlist('elements[]')
        page_obj = MyUser.objects.filter(id__in=uuids)
        context = {'page_obj': page_obj}
        if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
            result = render_to_string('myadmin/includes/table-users.html', request=request, context=context)
            return JsonResponse({'result': result})
        return render(request, 'myadmin/users/users-viewing.html', context=context)


class CategoriesListView(ListView, TitleMixin, UserDispatchMixin):
    """View to view list of all categories of the site in the admin panel."""
    model = QuestionCategory
    template_name = 'myadmin/categories/category-viewing.html'
    context_object_name = 'categories'
    title = 'Просмотр категорий'
    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        """
        Overrides the method of the parent class to optimize the query.
        Set slided page range in context.
        """
        context = super().get_context_data(**kwargs)
        context['objects']: QuestionCategory.objects.all().select_related()
        page = context['page_obj']
        context['paginator_range'] = page.paginator.get_elided_page_range(page.number)
        return context

    def get_queryset(self, order_val='id'):
        """Returns ordered queryset.

        Args:
            * order_val (str): Selected order value.

        Returns:
            * Queryset of ordered objects.
        """
        if self.request.GET.get('cat_order'):
            self.request.session['cat_order'] = self.request.GET.get('cat_order')
        if 'cat_order' in self.request.session:
            order_val = self.request.session['cat_order']
        return QuestionCategory.objects.all().order_by(order_val)


class CategoriesCreateView(CreateView, TitleMixin, UserDispatchMixin):

myadmin/templates/myadmin/includes/footer.html
<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid">
        <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright&copy;Lalluviadel 2022 Сайт создан исключительно в личных целях для некоммерческого использования</div>
        </div>
    </div>
</footer>

myadmin/templates/myadmin/includes/pagination.html
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
            <a class="page-link font-xl {% if page_obj.has_previous %} oranged {% endif %}"
               href="{% if page_obj.has_previous %} ?page={{ page_obj.previous_page_number }}
                               {% else %} # {% endif %}"
               tabindex="-1" aria-disabled="true">Previous</a>
        </li>

        {% for page in paginator_range|default_if_none:page_obj.paginator.get_elided_page_range %}
            {% if page_obj.number == page %}
                <li class="page-item">
                    <a class="page-link font-xl oranged-selected"
                       href="?page={{ page }}">{{ page }}</a>
                </li>

            {% else %}
                {% if page == page_obj.paginator.ELLIPSIS %}
                    <li class="page-item">
                                    <span class="page-link font-xl oranged"
                                          href="?page={{ page }}">{{ page }}</span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link font-xl oranged"
                           href="?page={{ page }}">{{ page }}</a>
                    </li>
                {% endif %}
            {% endif %}
        {% endfor %}

        <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
            <a class="page-link font-xl {% if page_obj.has_next %} oranged {% endif %}"
               href="{% if page_obj.has_next %} ?page={{ page_obj.next_page_number }}
                                     {% else %} # {% endif %}">Next</a>
        </li>
    </ul>

</nav>

myadmin/templates/myadmin/includes/table-categories.html
<div class="table-responsive">
    <table class="table table-bordered wigth-100 text-center" id="dataTable">
        <thead>
        <tr>
            <th>
                <a href="{% url 'myadmin:admins_categories' %}?cat_order=name" class="admin-link">
                    Название
                </a>
            </th>
            <th>Описание</th>
            <th>
                <a href="{% url 'myadmin:admins_categories' %}?cat_order=available" class="admin-link">
                    Активен
                </a>
            </th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th>Название</th>
            <th>Описание</th>
            <th>Активен</th>
        </tr>
        </tfoot>
        <tbody>
        {% for category in page_obj %}
            <tr{% if not category.available %} class="no-active" {% endif %}>
                <td class="col-2 text-left item-on-page" value="{{ category.id }}">
                    <a href="{% url 'myadmin:admins_category_update' category.id %}"
                       class="admin-link">{{ category.name }}</a>
                </td>
                <td class="col-9 text-left">{{ category.description }}</td>
                <td class="col-1">
                    <form id="update_cat_btn">
                        {% csrf_token %}
                        {% if category.available %}
                            <button name="{{ category.id }}" type="submit" class="btn btn-outline-dark btn-orange"><i
                                    class='fas fa-check-circle blacked'></i></button>
                        {% else %}
                            <button name="{{ category.id }}" type="submit" class="btn btn-outline-dark"><i
                                    class="fas fa-times-circle"></i></button>
                        {% endif %}
                    </form>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

myadmin/templates/myadmin/includes/table-posts.html
<div class="table-responsive">
    <table class="table table-bordered wigth-100 text-center" id="dataTable">
        <thead>
        <tr>
            <th>
                <a href="{% url 'myadmin:admins_posts' %}?post_order=title" class="admin-link">
                    Заголовок
                </a>
            </th>
            <th>
                <a href="{% url 'myadmin:admins_posts' %}?post_order=category" class="admin-link">
                    Категория
                </a>
            </th>
            <th>
                <a href="{% url 'myadmin:admins_posts' %}?post_order=created_on" class="admin-link">
                    Создана
                </a>
            </th>
            <th>
                <a href="{% url 'myadmin:admins_posts' %}?post_order=author" class="admin-link">
                    Автор
                </a>
            </th>
            <th>
                <a href="{% url 'myadmin:admins_posts' %}?post_order=tag" class="admin-link">
                    Тэг
                </a>
            </th>
            <th>
                <a href="{% url 'myadmin:admins_posts' %}?post_order=available" class="admin-link">
                    Активна
                </a>
            </th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th>Заголовок</th>
            <th>Категория</th>
            <th>Создана</th>
            <th>Автор</th>
            <th>Тэг</th>
            <th>Активна</th>
        </tr>
        </tfoot>
        <tbody>
        {% for post in page_obj %}
            <tr{% if not post.available %} class="no-active" {% endif %}>
                <td class="col-3 text-left item-on-page" value="{{ post.id }}">
                    <a href="{% url 'myadmin:admins_post_update' post.id %}"
                       class="admin-link">{{ post.title }}</a>
                </td>
                <td class="col-2 text-left">{{ post.category }}</td>
                <td class="col-2 text-left">{{ post.created_on }}</td>
                <td class="col-2 text-left">{{ post.author }}</td>
                <td class="col-2 text-left">{{ post.tag }}</td>
                <td class="col-1">
                    <form id="update_post_btn">
                        {% csrf_token %}
                        {% if post.available %}
                            <button name="{{ post.id }}" type="submit" class="btn btn-outline-dark btn-orange"><i
                                    class='fas fa-check-circle blacked'></i></button>
                        {% else %}
                            <button name="{{ post.id }}" type="submit" class="btn btn-outline-dark"><i
                                    class="fas fa-times-circle"></i></button>
                        {% endif %}
                    </form>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

myadmin/templates/myadmin/includes/table-questions.html
<div class="table-responsive">
    <table class="table table-bordered wigth-100 dtBasicExample" id="example">
        <thead>
            <tr>
                <th>Вопрос</th>
                <th>Категория</th>
                <th>
                    <a href="{% url 'myadmin:admins_questions' %}?que_order=author" class="admin-link">
                        Автор
                    </a>
                </th>
                <th>
                    <a href="{% url 'myadmin:admins_questions' %}?que_order=difficulty_level" class="admin-link">
                        Уровень
                    </a>
                </th>
                <th>Правильный ответ</th>
                <th>
                    <a href="{% url 'myadmin:admins_questions' %}?que_order=tag" class="admin-link">
                        Тег
                    </a>
                </th>
                <th>
                    <a href="{% url 'myadmin:admins_questions' %}?que_order=available" class="admin-link">
                        Активен
                    </a>
                </th>
            </tr>
        </thead>
        <tfoot>
        <tr>
            <th>Вопрос</th>
            <th>Категория</th>
            <th>Автор</th>
            <th>Уровень</th>
            <th>Правильный ответ</th>
            <th>Тег</th>
            <th>Активен</th>
        </tr>
        </tfoot>
        <tbody>
        {% for question in page_obj %}
            <tr {% if not question.available %} class="no-active" {% endif %}>
                <td class="text-left item-on-page" value="{{ question.id }}">
                    <a href="{% url 'myadmin:admins_question_update' question.id %}"
                       class="admin-link">
                    {{ question.question }}</a>
                </td>
                <td>{{ question.subject }}</td>
                <td>{{ question.author }}</td>
                <td>{{ question.difficulty_level }}</td>
                <td class="text-left">{{ question.right_answer }}</td>
                <td>{{ question.tag }}</td>
                <td class="text-center">
                    <form id="update_que_btn">
                        {% csrf_token %}
                        {% if question.available %}
                            <button name="{{ question.id }}" type="submit" class="btn btn-outline-dark btn-orange"><i
                                    class='fas fa-check-circle blacked'></i></button>
                        {% else %}
                            <button name="{{ question.id }}" type="submit" class="btn btn-outline-dark"><i
                                    class="fas fa-times-circle"></i></button>
                        {% endif %}
                    </form>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

myadmin/templates/myadmin/includes/table-users.html
<div class="table-responsive">
    <table class="table table-bordered wigth-100 dtBasicExample" id="example">
        <thead>
        <tr>
            <th>
                <a href="{% url 'myadmin:admins_users' %}?user_order=username" class="admin-link">
                    Никнейм
                </a>
            </th>
            <th>
                <a href="{% url 'myadmin:admins_users' %}?user_order=first_name" class="admin-link">
                    Имя
                </a>
            </th>
            <th>
                <a href="{% url 'myadmin:admins_users' %}?user_order=last_name" class="admin-link">
                    Фамилия
                </a>
            </th>
            <th>
                <a href="{% url 'myadmin:admins_users' %}?user_order=email" class="admin-link">
                    Email
                </a>
            </th>
            <th>
                <a href="{% url 'myadmin:admins_users' %}?user_order=score" class="admin-link">
                    Счет
                </a>
            </th>
            <th>
                <a href="{% url 'myadmin:admins_users' %}?user_order=is_staff" class="admin-link">
                    Персонал
                </a>
            </th>
            <th>
                <a href="{% url 'myadmin:admins_users' %}?user_order=is_active" class="admin-link">
                    Активен
                </a>
            </th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th>Никнейм</th>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Email</th>
            <th>Счет</th>
            <th>Персонал</th>
            <th>Активен</th>
        </tr>
        </tfoot>
        <tbody>
        {% for user in page_obj %}
            <tr {% if not user.is_active %} class="no-active"
            {% elif user.is_staff %} class="staff" {% endif %}>
                <td class="text-left item-on-page" value="{{ user.id }}">
                    <a href="{% url 'myadmin:admins_user_update' user.id %}"
                       class="admin-link">
                    {% if user.is_staff %}<i class="fa fa-star"></i>{% endif %}
                    {{ user.username }}</a>
                </td>
                <td>{{ user.first_name }}</td>
                <td>{{ user.last_name }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.score }}</td>
                <td class="text-center">
                    <form id="give_me_a_crown_btn">
                        {% csrf_token %}
                        {% if user.is_staff %}
                            <button name="{{ user.id }}" type="submit" class="btn btn-outline-dark btn-orange"><i
                                    class='fas fa-check-circle blacked'></i></button>
                        {% else %}
                            <button name="{{ user.id }}" type="submit" class="btn btn-outline-dark"><i
                                    class="fas fa-times-circle"></i></button>
                        {% endif %}
                    </form>
                </td>

                <td class="text-center">
                    <form id="update_user_btn">
                        {% csrf_token %}
                        {% if user.is_active %}
                            <button name="{{ user.id }}" type="submit" class="btn btn-outline-dark btn-orange"><i
                                    class='fas fa-check-circle blacked'></i></button>
                        {% else %}
                            <button name="{{ user.id }}" type="submit" class="btn btn-outline-dark"><i
                                    class="fas fa-times-circle"></i></button>
                        {% endif %}
                    </form>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>