interview_quiz/urls.py
from django.conf import settings
from django.conf.urls import handler404
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from graphene_django.views import GraphQLView
from rest_framework import routers
from rest_framework.permissions import AllowAny

from api_rest.api import QuestionCategoryViewSet, QuestionViewSet, PostViewSet, UserViewSet
from questions.views import MainView, my_handler404
from drf_yasg2.views import get_schema_view
from drf_yasg2 import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Interview Quiz",
      default_version='2.0',
      description="Documentation to Interview Quiz, my pet project",
      contact=openapi.Contact(email="inspiracion@yandex.ru"),
      license=openapi.License(name="MIT License"),
   ),
   public=True,
   permission_classes=(AllowAny,)
)

router = routers.DefaultRouter()
router.register('categories', QuestionCategoryViewSet)
router.register('questions', QuestionViewSet)
router.register('posts', PostViewSet)
router.register('users', UserViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainView.as_view(), name='index'),
    path('questions/', include('questions.urls', namespace='questions')),
    path('users/', include('users.urls', namespace='users')),
    path('myadmin/', include('myadmin.urls', namespace='myadmin')),
    path('posts/', include('posts.urls', namespace='posts')),

    path('', include('social_django.urls', namespace='social')),

    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include(router.urls)),

    re_path(r'^swagger(?P<format>\.json|\.yaml)$',
    schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0),
    name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0),
    name='schema-redoc'),

    path('graphql/', GraphQLView.as_view(graphiql=True)),
]

handler404 = 'questions.views.my_handler404'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r'^__debug_/', include(debug_toolbar.urls))]
    urlpatterns += [path('404/', my_handler404, kwargs={'exception':
                                                            Exception('Page not Found')}, name='page_404')]

myadmin/urls.py
"""Sets associations of myadmin application urls with their views.

Attributes:

    * app_name (str): the name of a specific web application used in different parts of the overall structure.
    * urlpatterns(list): a list of paths that determine the behavior of a web application
                        when using the urls specified in the list.

"""

from django.urls import path

from .views import AdminPanelView, UserListView, UserUpdateView, UserDeleteView, \
    UserCreateView, CategoriesListView, CategoriesUpdateView, \
    CategoriesCreateView, CategoriesDeleteView, QuestionListView, QuestionCreateView, QuestionUpdateView, \
    QuestionDeleteView, PostListView, PostCreateView, PostUpdateView, PostDeleteView, UserIsStaff, \
    AdminsSearchQuestionView, AdminsSearchPostView, AdminsSearchUserView, AdminsSearchCategoryView, \
    AllTagsQuestionsView, ListQuestionsByTagView, AllTagsPostsView, ListPostsByTagView

app_name = 'myadmin'
urlpatterns = [
    path('', AdminPanelView.as_view(), name='admins_index'),
    path('users/', UserListView.as_view(), name='admins_users'),
    path('users-create/', UserCreateView.as_view(), name='admins_user_create'),
    path('users-update/<uuid:pk>/', UserUpdateView.as_view(), name='admins_user_update'),
    path('users-delete/<uuid:pk>/', UserDeleteView.as_view(), name='admins_user_delete'),

    path('users-is-staff/<uuid:pk>/', UserIsStaff.as_view(), name='admins_user_is_staff'),

    path('categories/', CategoriesListView.as_view(), name='admins_categories'),
    path('categories-create/', CategoriesCreateView.as_view(), name='admins_category_create'),
    path('categories-update/<int:pk>/', CategoriesUpdateView.as_view(), name='admins_category_update'),
    path('categories-delete/<int:pk>/', CategoriesDeleteView.as_view(), name='admins_category_delete'),

    path('questions/', QuestionListView.as_view(), name='admins_questions'),
    path('questions-create/', QuestionCreateView.as_view(), name='admins_question_create'),
    path('questions-update/<int:pk>/', QuestionUpdateView.as_view(), name='admins_question_update'),
    path('questions-delete/<int:pk>/', QuestionDeleteView.as_view(), name='admins_question_delete'),
    path('questions-tags/', AllTagsQuestionsView.as_view(), name='admins_question_tags'),
    path('questions-by-tag/<str:pk>/', ListQuestionsByTagView.as_view(), name='admins_questions_by_tag'),

    path('posts/', PostListView.as_view(), name='admins_posts'),
    path('posts-create/', PostCreateView.as_view(), name='admins_post_create'),
    path('posts-update/<int:pk>/', PostUpdateView.as_view(), name='admins_post_update'),
    path('posts-delete/<int:pk>/', PostDeleteView.as_view(), name='admins_post_delete'),
    path('posts-tags/', AllTagsPostsView.as_view(), name='admins_post_tags'),
    path('posts-by-tag/<str:pk>/', ListPostsByTagView.as_view(), name='admins_posts_by_tag'),

    path('search/user/', AdminsSearchUserView.as_view(), name='admins_search_results_user'),
    path('search/cat/', AdminsSearchCategoryView.as_view(), name='admins_search_results_category'),
    path('search/question/', AdminsSearchQuestionView.as_view(), name='admins_search_results_question'),
    path('search/post/', AdminsSearchPostView.as_view(), name='admins_search_results_post'),
]

posts/urls.py
"""Sets associations of posts application urls with their views.

Attributes:

    * app_name (str): the name of a specific web application used in different parts of the overall structure.
    * urlpatterns(list): a list of paths that determine the behavior of a web application
                         when using the urls specified in the list.
"""
from django.urls import path

from .views import PostView, PostsCategoryView, UserPostView, TagPostView, CategoryPostView, SearchPostView

app_name = 'posts'
urlpatterns = [
    path('all/', PostsCategoryView.as_view(), name='all'),
    path('post/<int:pk>/', PostView.as_view(), name='post'),
    path('user_posts/<uuid:pk>/', UserPostView.as_view(), name='user_posts'),
    path('tag_posts/<str:tag>/', TagPostView.as_view(), name='tag_posts'),
    path('category_posts/<int:pk>/', CategoryPostView.as_view(), name='category_posts'),

    path('search/', SearchPostView.as_view(), name='search_results_post'),
]

questions/urls.py
"""Sets associations of questions application urls with their views.

Attributes:

    * app_name (str): the name of a specific web application used in different parts of the overall structure.
    * urlpatterns(list): a list of paths that determine the behavior of a web application
                         when using the urls specified in the list.
"""

from django.urls import path

from questions.views import CategoryView, QuestionView, AllCategoriesView, \
    TimeIsUp, AnswerQuestion

app_name = 'questions'
urlpatterns = [
    path('categories/', AllCategoriesView.as_view(), name='categories'),
    path('start_test/<int:pk>/', CategoryView.as_view(), name='start_test'),
    path('test_body/<int:pk>/', QuestionView.as_view(), name='test_body'),
    path('answers/<int:item_id>/', AnswerQuestion.as_view(), name='answers'),
    path('time_is_up/', TimeIsUp.as_view(), name='time_is_up'),
]

myadmin/views.py
"""The submodule contains views for convenient and correct work with all the main entities of the
project within the admin panel.

There are views:

    * for standard work with objects according to the CRUD principle;
    * for searching for users, posts, categories and questions by a given mask (word or part of a word);
    * to grant or remove administrator rights to a user;

To reduce code duplication, two parent classes are used.
"""

from django.db.models import Q
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView

from interview_quiz.mixin import TitleMixin, UserDispatchMixin
from myadmin.forms import UserAdminRegisterForm, UserAdminProfileForm, CategoryForm, QuestionForm, PostForm
from posts.models import Post
from questions.models import QuestionCategory, Question
from users.models import MyUser


class BaseListView(ListView, TitleMixin, UserDispatchMixin):
    """Parent class for QuestionListView and PostListView, required to comply with the DRY pattern."""

    def get_context_data(self, *, object_list=None, **kwargs):
        """Provides getting and saving the current category selected by the user.
        The current category is saved in the session.
        When all categories are selected (no filter), the current category in the session is reset to zero.
        Set slided page range in context.
        """
        context = super().get_context_data(**kwargs)
        context['categories'] = QuestionCategory.objects.all()
        if self.request.GET.get('filter'):
            if self.request.GET.get('filter') == 'all':
                self.request.session['current_category'] = None
                return context
            context['current_category'] = QuestionCategory.objects.get(id=self.request.GET.get('filter')).name
            self.request.session['current_category'] = context['current_category']
        elif 'current_category' in self.request.session:
            context['current_category'] = self.request.session['current_category']
        page = context['page_obj']
        context['paginator_range'] = page.paginator.get_elided_page_range(page.number)
        return context


class BaseDeleteView(DeleteView, UserDispatchMixin):
    """Parent class for QuestionDeleteView and PostDeleteView, required to comply with the DRY pattern."""

    def delete(self, request, flag='false', *args, **kwargs):
        """Performs complete deletion or activation/deactivation of the object
        in accordance with the specified mode of action.

        Args:
            * request: standard parameter.
            * flag(str, optional): the default value is 'false'. A switch parameter that allows you
                                 to specify the mode of deleting an object: completely deleting an
                                 entry from the database or marking the object as inactive.
            * ``*args``: standard parameter.
            * ``**kwargs``: standard parameter.
        """
        item = self.get_object()
        if 'flag' in request.POST:
            flag = request.POST['flag']
        if flag == 'false':
            item.available = False if item.available is True else True
            item.save()
        else:
            item.delete()


class AdminPanelView(TemplateView, TitleMixin, UserDispatchMixin):
    """View for the main admin page."""
    template_name = 'myadmin/admin.html'
    title = 'Админка'


class UserListView(ListView, TitleMixin, UserDispatchMixin):
    """View to view lists of all registered users of the site in the admin panel."""
    model = MyUser
    template_name = 'myadmin/users/users-viewing.html'
    context_object_name = 'users'
    title = 'Просмотр пользователей'
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        """Set slided page range in context."""
        context = super().get_context_data(**kwargs)
        page = context['page_obj']
        context['paginator_range'] = page.paginator.get_elided_page_range(page.number)
        return context

    def get_queryset(self, order_val='date_joined'):
        """Returns ordered queryset.

        Args:
            * order_val (str): Selected order value.

        Returns:
            * Queryset of ordered objects.
        """
        if self.request.GET.get('user_order'):
            self.request.session['user_order'] = self.request.GET.get('user_order')
        if 'user_order' in self.request.session:
            order_val = self.request.session['user_order']
        return MyUser.objects.all().order_by(order_val)


class UserCreateView(CreateView, TitleMixin, UserDispatchMixin):
    """View to create a new user in the admin panel."""
    model = MyUser
    template_name = 'myadmin/users/users-creating.html'
    form_class = UserAdminRegisterForm
    success_url = reverse_lazy('myadmin:admins_users')
    title = 'Добавить пользователя'


class UserUpdateView(UpdateView, TitleMixin, UserDispatchMixin):
    """View to update a specific user in the admin panel."""
    model = MyUser
    template_name = 'myadmin/users/users-update.html'
    form_class = UserAdminProfileForm
    success_url = reverse_lazy('myadmin:admins_users')
    title = 'Изменить пользователя'


class UserDeleteView(DeleteView, UserDispatchMixin):
    """View to delete or activate/deactivate a specific user in the admin panel."""
    model = MyUser
    template_name = 'myadmin/users/users-update.html'
    success_url = reverse_lazy('myadmin:admins_users')

    def delete(self, request, flag='false', *args, **kwargs):
        """Performs complete deletion or activation/deactivation of the user
        in accordance with the specified mode of action.

        Args:
            * request: standard parameter.
            * flag(str, optional): the default value is 'false'. A switch parameter that allows you
                                 to specify the mode of deleting an object: completely deleting an
                                 entry from the database or marking the object as inactive.
            * ``*args``: standard parameter.
            * ``**kwargs``: standard parameter.
        """
        item = self.get_object()
        if 'flag' in request.POST:
            flag = request.POST['flag']
        if request.user.id != kwargs['pk']:
            if flag == 'false':
                item.is_active = False if item.is_active is True else True
                item.save()
            else:
                item.delete()

    def post(self, request, *args, **kwargs):
        """Starts the process of deleting or activating/deactivating user.
        When enabled ajax, returns data for an asynchronous web request"""
        self.delete(request, *args, **kwargs)
        if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
            uuids = request.POST.getlist('elements[]')

            page_obj = MyUser.objects.filter(id__in=uuids)
            context = {'page_obj': page_obj}

            result = render_to_string('myadmin/includes/table-users.html', request=request, context=context)
            return JsonResponse({'result': result})
        return HttpResponseRedirect(reverse('myadmin:admins_user_update', kwargs=kwargs))


class UserIsStaff(UpdateView, UserDispatchMixin):
    """View for granting the user rights/removing the rights of the superuser in the admin panel."""
    model = MyUser
    form_class = UserAdminProfileForm
    template_name = 'myadmin/includes/table-users.html'

    def post(self, request, *args, **kwargs):
        """Sets superuser rights for the selected user or deletes them.
        When enabled ajax, returns data for an asynchronous web request."""
        user = get_object_or_404(MyUser, pk=kwargs['pk'])
        if self.request.user != user:
            user.is_staff = False if user.is_staff is True else True
            user.save()
        uuids = request.POST.getlist('elements[]')
        page_obj = MyUser.objects.filter(id__in=uuids)
        context = {'page_obj': page_obj}
        if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
            result = render_to_string('myadmin/includes/table-users.html', request=request, context=context)
            return JsonResponse({'result': result})
        return render(request, 'myadmin/users/users-viewing.html', context=context)


class CategoriesListView(ListView, TitleMixin, UserDispatchMixin):
    """View to view list of all categories of the site in the admin panel."""
    model = QuestionCategory
    template_name = 'myadmin/categories/category-viewing.html'
    context_object_name = 'categories'
    title = 'Просмотр категорий'
    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        """
        Overrides the method of the parent class to optimize the query.
        Set slided page range in context.
        """
        context = super().get_context_data(**kwargs)
        context['objects']: QuestionCategory.objects.all().select_related()
        page = context['page_obj']
        context['paginator_range'] = page.paginator.get_elided_page_range(page.number)
        return context

    def get_queryset(self, order_val='id'):
        """Returns ordered queryset.

        Args:
            * order_val (str): Selected order value.

        Returns:
            * Queryset of ordered objects.
        """
        if self.request.GET.get('cat_order'):
            self.request.session['cat_order'] = self.request.GET.get('cat_order')
        if 'cat_order' in self.request.session:
            order_val = self.request.session['cat_order']
        return QuestionCategory.objects.all().order_by(order_val)


class CategoriesCreateView(CreateView, TitleMixin, UserDispatchMixin):

myadmin/templates/myadmin/questions/all_question_tags.html
{% extends 'myadmin/base.html' %}
{% load static %}


{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid text-center mb-1">
                {% if object_list %}

                    <h1 class="mt-4">Все теги вопросов:</h1>
                    <div class="text-justify mt-4">

                        {% for tag in object_list %}
                            <ul class="list-group">
                                <li class="list-group-item">
                                    <a href="{% url 'myadmin:admins_questions_by_tag' tag %}" class="admin-link">
                                        {{ tag }}
                                    </a>
                                </li>
                            </ul>
                        {% endfor %}

                    </div>
                {% endif %}
            </div>
        </main>
        {% include 'myadmin/includes/footer.html' %}
    </div>
{% endblock %}

myadmin/templates/myadmin/questions/question-update.html
{% extends 'myadmin/base.html' %}
{% load static %}


{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4 text-center">Редактирование вопроса</h1>
                <h2 class="text-center"><b class="oranged">{{ question.question }}</b></h2>
                <div class="card-body">
                    <form action="{% url 'myadmin:admins_question_update' question.id %}" method="post"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.question.id_for_label }}">Текст
                                        вопроса</label>
                                    {{ form.question }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.subject.id_for_label }}">Категория</label>
                                    {{ form.subject }}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1"
                                           for="{{ form.difficulty_level.id_for_label }}">Сложность</label>
                                    {{ form.difficulty_level }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.right_answer.id_for_label }}">Правильный
                                        ответ</label>
                                    {{ form.right_answer }}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.tag.id_for_label }}">Тег</label>
                                    {{ form.tag }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.answer_01.id_for_label }}">Ответ 1</label>
                                    {{ form.answer_01 }}
                                </div>
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.answer_03.id_for_label }}">Ответ 3</label>
                                    {{ form.answer_03 }}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.answer_02.id_for_label }}">Ответ 2</label>
                                    {{ form.answer_02 }}
                                </div>
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.answer_04.id_for_label }}">Ответ 4</label>
                                    {{ form.answer_04 }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row text-center">
                            <div class="col-lg-4">
                                <p class="text-center">Картинка для вопроса</p>
                                <img width="300" height="300"
                                     src="{% if question.image_01 %} {{ question.image_01.url }} {% else %} {% static 'vendor/img/no_image.png' %} {% endif %}"
                                     class="img-thumbnail" alt="">
                                <div class="custom-file">
                                    {{ form.image_01 }}
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <p class="text-center">Картинка 1 для пояснения ответа</p>
                                <img width="300" height="300"
                                     src="{% if question.image_02 %} {{ question.image_02.url }} {% else %} {% static 'vendor/img/no_image.png' %} {% endif %}"
                                     class="img-thumbnail" alt="">
                                <div class="custom-file">
                                    {{ form.image_02 }}
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <p class="text-center">Картинка 2 для пояснения ответа</p>
                                <img width="300" height="300"
                                     src="{% if question.image_03 %} {{ question.image_03.url }} {% else %} {% static 'vendor/img/no_image.png' %} {% endif %}"
                                     class="img-thumbnail" alt="">
                                <div class="custom-file">
                                    {{ form.image_03 }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row mt-lg-5">
                            <div class="col-lg-4">
                                <input type="button" class="btn btn-secondary btn-block"
                                       onclick="window.location.href = '{% url 'myadmin:admins_questions' %}';"
                                       value="Отмена"/>
                            </div>
                            <div class="col-lg-4">
                                <input class="btn btn-outline-dark btn-orange btn-block" type="submit"
                                       value="Сохранить">
                            </div>
                            <div class="col-lg-4">
                                {% if question.available %}
                                    <form action="{% url 'myadmin:admins_question_delete' question.id %}"
                                          method="post">
                                    </form>
                                    <form action="{% url 'myadmin:admins_question_delete' question.id %}"
                                          method="post">
                                        {% csrf_token %}
                                        <input class="btn btn-dark btn-block"
                                               value="Деактивировать"
                                               type="submit">
                                    </form>
                                    </div>
                                {% else %}
                                    <form action="{% url 'myadmin:admins_question_delete' question.id %}"
                                          method="post">
                                    </form>
                                    <form action="{% url 'myadmin:admins_question_delete' question.id %}"
                                          method="post">
                                        {% csrf_token %}
                                        <input class="btn btn-outline-dark btn-block"
                                               value="Активировать"
                                               type="submit">
                                    </form>
                                {% endif %}
                        </div>
                    </form>
                </div>
            </div>
        </main>
        {% include 'myadmin/includes/footer.html' %}
    </div>
{% endblock %}

myadmin/templates/myadmin/questions/question-viewing.html
{% extends 'myadmin/base.html' %}
{% load static %}


{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid text-center">
                <h1 class="mt-4">Вопросы {% if current_category %}категории {{ current_category }} {% endif %}</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-5">
                                <ul class="text-left">
                                    <li>Для редактирования клик на вопросе</li>
                                    <li>Для удаления (деактивации) - кнопка в графе Активен</li>
                                </ul>
                            </div>
                            <div class="col-5">
                                <form method="get" action="{% url 'myadmin:admins_questions' %}">
                                    <div class="row">
                                        <div class="col-3"><label for="filter">Фильтр по категориям: </label></div>
                                        <div class="col-6"><select name="filter" class="form-control" id="filter">
                                            <option value="all" selected name="filter">Все категории</option>
                                            {% for category in categories %}
                                                <option value="{{ category.id }}" name="filter">{{ category }}</option>
                                            {% endfor %}
                                        </select></div>
                                        <div class="col-3"><input class="btn btn-outline-dark btn-orange" type="submit"
                                                                  value="Ок"></div>
                                    </div>
                                </form>
                            </div>
                            <div class="col-2">
                                <form method="get" action="{% url 'myadmin:admins_question_tags' %}">
                                    <div class="col-3">
                                        <input class="btn btn-primary" type="submit" value="Все теги">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div id="update_que_catcher" class="card-body">

                        <div class="col-md-7 float-left">
                            <p id="text" style="display:none"><i class="fa fa-bomb oranged font-xl"></i> В режиме
                                "Удаление" элементы будут полностью удалены</p>
                        </div>
                        <div class="col-md-4 float-right mb-2">
                            <div class="btn-group btn-group-toggle btn-block" id="deact_delete"
                                 data-toggle="buttons">
                                <label class="btn btn-primary active mr-1">
                                    <input type="radio" name="options" id="option1" autocomplete="off" checked>
                                    Деактив
                                </label>
                                <label class="btn btn-primary mr-1">
                                    <input type="radio" name="options" id="option2" autocomplete="off"> Удаление
                                </label>
                            </div>
                        </div>

                        {% include 'myadmin/includes/table-questions.html' %}

                    </div>
                    <div class="card-footer">
                        <a href="{% url 'myadmin:admins_question_create' %}">
                            <button class="btn btn-outline-dark btn-orange">Создать вопрос</button>
                        </a>
                    </div>
                </div>

                {% include 'myadmin/includes/pagination.html' %}

            </div>
        </main>
        {% include 'myadmin/includes/footer.html' %}
    </div>
{% endblock %}